name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  rust_version: 1.70.0

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: ${{ env.rust_version }}
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings
      - run: cargo test --doc

  test:
    strategy:
      matrix:
        include:
          - os: macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: ${{ env.rust_version }}
      - run: cargo build --all-targets --verbose
      - run: cargo test --release
      - run: cd solace-rs-sys && cargo test --release


# github actions only supports container services on ubuntu
  integration-test:
    services:
      solace:
        image: solace/solace-pubsub-standard:10.5
        options: --shm-size=1gb
        env: 
          username_admin_globalaccesslevel: admin
          username_admin_password: admin
          system_scaling_maxconnectioncount: 100
        ports:
          - 55555:55555
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: ${{ env.rust_version }}
      - run: cargo build --all-targets --verbose
      - run: cargo test --release
      - run: cargo test --release -- --ignored
        env:
          SOLACE_HOST: 0.0.0.0
          SOLACE_PORT: ${{ job.services.solace.ports[55555] }}
      - run: cd solace-rs-sys && cargo test --release

